name: Upload to ESOUI

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip addon folder
        run: |
          zip -r QuickBank.zip QuickBank


      - name: Upload to ESOUI
        uses: m00nyONE/esoui-upload@v1
        with:
          api_key: ${{ secrets.ESOUI_ADDON_UPDATE }}
          addon_id: 4109
          version: v1.0.0
          zip_file: QuickBank.zip
          changelog_file: CHANGELOG.txt
